runtime: nodejs18
service: cicv

# Pengaturan lingkungan (jika diperlukan)
env_variables:
  KEY: "VALUE"

# Aturan handler
handlers:
  - url: /static
    static_dir: static
    # Menangani file statis dalam direktori 'static'

  - url: /.*
    script: auto
    # Diteruskan ke aplikasi Node.js untuk penanganan dinamis
