runtime: nodejs18

beta_settings:
  cloud_sql_instances: "optical-precept-406804:asia-southeast2:signuplogin"

env_variables:
  DB_HOST: "34.101.209.252"
  DB_USER: "root"
  DB_PASSWORD: "TesAdmin123"
  DB_NAME: "node_api"

# Pengaturan lingkungan (jika diperlukan)
env_variables:
  KEY: "VALUE"

# Aturan handler
handlers:
  - url: /static
    static_dir: static
    # Menangani file statis dalam direktori 'static'

  - url: /.*
    script: auto
    # Diteruskan ke aplikasi Node.js untuk penanganan dinamis